services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game-store
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - 3308:3306